version: "3.9"
services:
  web:
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/code
      - models:/persisted_models
    ports:
      - "5000:5000"

volumes:
  models: {}
